# cloudbuild.yaml
steps:
-  name: maven:3-jdk-8
   entrypoint: mvn
   args:
   - package
-  name: gcr.io/cloud-builders/gcloud
   args:
   - app
   - deploy
   timeout: 1600s
# Build the container image
-  name: gcr.io/cloud-builders/docker
   args:
   - build
   - -t
   - gcr.io/$PROJECT_ID/example1
# Deploy container image to Cloud Run
   - --build-arg=JAR_FILE=target/example1-0.0.1-SNAPSHOT.jar
   - .
# Push the container image to Container Registry
-  name: gcr.io/cloud-builders/docker
   args:
   - push
   - gcr.io/$PROJECT_ID/example1
-  name: gcr.io/cloud-builders/gcloud
   args:
   - run
   - deploy
   - myservice
   - --image
   - gcr.io/$PROJECT_ID/example1
   - --region
   - us-central1
   - --platform
   - managed
   - --allow-unauthenticated
images:
- gcr.io/$PROJECT_ID/example1